config/routes.rb
Rails.application.routes.draw do

  root 'feeds#index'
  get 'links' => 'feeds#links'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  URLS = %w[https://scotthelme.co.uk/rss/ https://www.schneier.com/blog/atom.xml http://feeds.wired.com/WiredDangerRoom http://feeds.wired.com/wired27b http://feeds2.feedburner.com/RogersInfosecBlog http://www.darkreading.com/rss_simple.asp http://krebsonsecurity.com/feed/ http://dankaminsky.com/feed/]

  def self.feeds
    [].tap do |feeds|
      URLS.each do |url|
        feeds << Feedjira::Feed.fetch_and_parse(url)
      end
    end
  end

  def self.feed_entries
    entries = []
    Feed.feeds.each do |feed|
      entries += feed.entries
    end
    entries.sort_by { |feed| feed.published }.reverse
  end

  def self.readable_date(date)
    date.strftime("%A, %b %d")
  end

  def self.author(author)
    author || "Unknown"
  end

  def self.links_array
    URLS.each do
      fail
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @entries = Feed.feed_entries
  end

  def links
    # @links = Feeds.links_array
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/index.html.erb
<!-- <%= link_to "What feeds are being used?", links_url %> -->

<% @entries.each do |entry| %>
  <div class='entry'>
    <h1><%= entry.title %></h1>
    <h6><%= Feed.readable_date entry.published %> - Posted by <%= Feed.author(entry.author) %> at<br /><%= link_to "#{entry.url[0,50] + "..."}", entry.url %></h6>
  </div>
<% end %>

app/views/feeds/links.html.erb
<%= link_to "Back", :back %><br />

<ul>
  <% .each do |link| %>
    <li><%= link %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssReader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h3>RSS Feed</h3>
<%= yield %>

</body>
</html>